/**
 * SatQuery AI — Enhanced Report Generator
 * Produces a structured downloadable analysis report (PDF & JSON)
 * GEO-MINDS Team
 */

import type { AnalysisResult, RasterSlot } from "./types";
import type { AgentPlan } from "./agent-router";

function downloadBlob(blob: Blob, name: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = name;
  a.click();
  URL.revokeObjectURL(url);
}

function pdfEscape(s: string) {
  return s.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)").replace(/[^\x20-\x7E]/g, "?");
}

export function exportFullReport(
  analysis: AnalysisResult,
  primary: RasterSlot,
  plan: AgentPlan,
  query: string,
  before?: RasterSlot,
) {
  const ts = new Date().toISOString();
  const confLabel = `${plan.confidenceScore}% (${plan.confidence.toUpperCase()}) — ${plan.confidenceNote}`;

  const lines: string[] = [
    "SATQUERY AI — ANALYSIS REPORT",
    "Team: GEO-MINDS",
    "=".repeat(56),
    "",
    `Timestamp: ${ts}`,
    `Query: ${query}`,
    "",
    "INPUT INFORMATION",
    `  Primary image: ${primary.name}  (${primary.width}×${primary.height} px, GSD ${primary.gsdMeters}m)`,
    before ? `  Before image: ${before.name}` : "  Mode: Single Image",
    `  Input mode: ${plan.inputMode}`,
    "",
    "AGENTIC PIPELINE",
    `  Detected task: ${plan.taskLabel}`,
    `  Selected specialists:`,
    ...plan.specialists.map((s) => `    • ${s.name} [${s.status.toUpperCase()}] — ${s.description}`),
    "",
    "EXECUTION TRACE",
    ...plan.trace.map((t) => `  ${t.status === "ok" ? "✓" : t.status === "warn" ? "⚠" : "○"} ${t.label}${t.detail ? " · " + t.detail : ""}`),
    "",
    "RESULT",
    `  Answer: ${analysis.answer}`,
    analysis.sceneSummary ? `  Scene summary: ${analysis.sceneSummary}` : "",
    "",
    "CONFIDENCE",
    `  ${confLabel}`,
    "",
    "EVIDENCE",
    ...plan.evidenceFactors.map((f) => `  • ${f}`),
    "",
    "LAND COVER STATISTICS",
    ...analysis.statistics.slice(0, 10).map((s) => `  ${s.name}: ${s.value}${s.hint ? " (" + s.hint + ")" : ""}`),
    "",
    analysis.change
      ? [
          "CHANGE ANALYSIS",
          `  Pixel change: ${analysis.change.percent.toFixed(1)}%`,
          `  Summary: ${analysis.change.summary}`,
          "",
        ].join("\n")
      : "",
    "DETECTIONS",
    `  ${analysis.detections.length} regions detected`,
    ...analysis.detections.slice(0, 8).map(
      (d) =>
        `  [${d.id}] ${d.label}  conf:${(d.confidence * 100).toFixed(0)}%  bbox:[${d.bbox.map((v) => v.toFixed(3)).join(",")}]`,
    ),
    "",
    "MODEL REGISTRY (DEMO/PROTOTYPE)",
    "  Note: Some specialist models are in stub/demo mode.",
    "  Confidence is estimated, not statistically calibrated.",
    plan.demoMode ? "  ⚠ DEMO MODE: Simulated inference components present." : "  ✓ Real VLM inference active (Gemini / xAI).",
    "",
    "=".repeat(56),
    "SatQuery AI · GEO-MINDS · Generated by agentic pipeline",
  ].filter((l) => l !== "");

  // Wrap at 88 chars
  const wrapped: string[] = [];
  for (const line of lines) {
    const chunks = line.match(/.{1,88}/g) ?? [""];
    wrapped.push(...chunks);
  }

  const content = wrapped
    .slice(0, 55)
    .map((l, i) => `BT /F1 10 Tf 40 ${790 - i * 14} Td (${pdfEscape(l)}) Tj ET`)
    .join("\n");

  const objects = [
    "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
    "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
    "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >> endobj",
    `4 0 obj << /Length ${content.length} >> stream\n${content}\nendstream endobj`,
    "5 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
  ];

  let offset = 9;
  const xref = [0];
  let body = "%PDF-1.4\n";
  for (const obj of objects) {
    xref.push(offset);
    body += obj + "\n";
    offset = body.length;
  }
  const startxref = body.length;
  body += `xref\n0 ${objects.length + 1}\n`;
  body += "0000000000 65535 f \n";
  for (const x of xref.slice(1)) body += `${String(x).padStart(10, "0")} 00000 n \n`;
  body += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${startxref}\n%%EOF`;

  downloadBlob(new Blob([body], { type: "application/pdf" }), "satquery-report.pdf");
}

export function exportFullJson(
  analysis: AnalysisResult,
  primary: RasterSlot,
  plan: AgentPlan,
  query: string,
  before?: RasterSlot,
) {
  const report = {
    meta: {
      tool: "SatQuery AI",
      team: "GEO-MINDS",
      generatedAt: new Date().toISOString(),
      version: "2.0",
    },
    input: {
      query,
      primary: { name: primary.name, width: primary.width, height: primary.height, gsdMeters: primary.gsdMeters },
      before: before ? { name: before.name, width: before.width, height: before.height } : null,
      inputMode: plan.inputMode,
    },
    agentPlan: {
      task: plan.task,
      taskLabel: plan.taskLabel,
      inputMode: plan.inputMode,
      specialists: plan.specialists,
      trace: plan.trace,
    },
    result: {
      answer: analysis.answer,
      sceneSummary: analysis.sceneSummary,
      intent: analysis.intent,
      highlightedTarget: analysis.highlightedTarget,
      detections: analysis.detections,
      segments: analysis.segments,
      statistics: analysis.statistics,
      change: analysis.change
        ? {
            percent: analysis.change.percent,
            summary: analysis.change.summary,
            regions: analysis.change.regions,
          }
        : null,
    },
    confidence: {
      score: plan.confidenceScore,
      level: plan.confidence,
      note: plan.confidenceNote,
    },
    evidence: {
      factors: plan.evidenceFactors,
      whyResult: plan.whyResult,
    },
    disclaimer: plan.demoMode
      ? "Some specialist models are in STUB/DEMO mode. Results include simulated inference components."
      : "Real VLM inference active (Gemini / xAI). Local analysis uses spectral heuristics.",
  };

  downloadBlob(
    new Blob([JSON.stringify(report, null, 2)], { type: "application/json" }),
    "satquery-report.json",
  );
}
